In [74]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [3]:
# import data and read data
df = pd.read_csv("D:\MACHINE LEARNING\Machine Learning\CSV FILE\emails.csv")
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
# data preprocessing
df["spam"].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [5]:
# drop duplicates values
df.drop_duplicates(inplace=True)

In [6]:
df["spam"].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [7]:
# check null value
df.isnull().sum()

text    0
spam    0
dtype: int64

In [8]:
# seperate featurs and level
x = df.text.values
y = df.spam.values

In [9]:
x

array(["Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : y

In [13]:
# split the data sets
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=1)

In [18]:
# Data preprocessing
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
# Model selection
model = MultinomialNB()
model.fit(x_train,ytrain)


MultinomialNB()

In [21]:
x_test = cv.transform(xtest)
x_test2 = cv.fit_transform(xtest)

In [29]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
x_test2.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
# see accuracy
accuracy = model.score(x_test,ytest)
print("Accuracy: ",round(accuracy*100,ndigits=3),"%")

Accuracy:  99.385 %


In [65]:
# predict by one emails
email = ['hey i am looking python tutorial in english language','hey you will win iphone x if you give your correct information for our survey',]

In [66]:
cv_email = cv.transform(email)

In [71]:
pred_vlaue = model.predict(x_test)
pred_vlaue

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [67]:
cv_email.toarray()

array([[1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 1]],
      dtype=int64)

In [68]:
cv.get_feature_names()

['am',
 'correct',
 'english',
 'for',
 'give',
 'hey',
 'if',
 'in',
 'information',
 'iphone',
 'language',
 'looking',
 'our',
 'python',
 'survey',
 'tutorial',
 'will',
 'win',
 'you',
 'your']

In [72]:
# model.predict(cv_email)


In [75]:
# Performance calculate
Accuracy_score = accuracy_score(ytest,pred_vlaue)
print("Accuracy score: ",round(Accuracy_score*100,ndigits=3),"%")

Accuracy score:  99.385 %


In [77]:
Confusion_matrix = confusion_matrix(ytest,pred_vlaue)
print(Confusion_matrix)

[[863   3]
 [  4 269]]


In [78]:
print(classification_report(ytest,pred_vlaue))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       866
           1       0.99      0.99      0.99       273

    accuracy                           0.99      1139
   macro avg       0.99      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

